# Setup
title:        Cytoflow
tagline:      Better quantitative flow cytometry.
version:      0.9.3
baseurl:      "/cytoflow"
paginate:     1

# About/contact
author:  
  name:       Brian Teague
  url:        https://brian.teague.name

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
