environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\packaging\\appveyor\\run_with_compiler.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.

    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6.x"   # currently 3.5.2
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6.x"       # currently 3.5.2
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_repo_commit.substring(0,7))"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  
  # install swig
  - choco install swig --version 3.0.2 --yes --limit-output

  # Install the build and runtime dependencies of the project.
  - conda update --yes conda
  - conda config --add channels bpteague
  - conda install --yes --quiet anaconda-client conda-build

  # Set up conda recipe variables
  - IF "%APPVEYOR_REPO_TAG%"=="true" (set CONDA_TAG=%APPVEYOR_REPO_TAG_NAME%) ELSE (set CONDA_TAG=dev)
  - IF "%APPVEYOR_REPO_TAG%"=="true" (set CONDA_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%) ELSE (set CONDA_BUILD_NUMBER=0)
  - set CONDA_BUILD_STRING=py35_win%PYTHON_ARCH%_%CONDA_BUILD_NUMBER%
  
  # Build the conda package
  - conda render packaging\conda_recipes\cytoflow
  - "%WITH_COMPILER% conda build packaging\\conda_recipes\\cytoflow"
  
  # Install the new package locally
  - conda create --yes --quiet --name=cytoflow python=3.6.6
  - activate cytoflow
  - conda install --yes --quiet --use-local --only-deps cytoflow
  - "%WITH_COMPILER% python setup.py develop"
  
  # have to (re)overwrite the SWIG-generated extension
  - git reset --hard
  
  # Check again for the expected version and architecture for Python
#  - "python --version"
#  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  
  # - conda install --yes --quiet mkl=2017.0.3-0  # new version of mkl has bad interaction with numpy
  - conda install --yes --quiet msvc_runtime pip mock

  # Install test requirements
  - pip.exe install nose2 

build: off

test_script:
  - "nose2 -c packaging\\nose2.cfg -s cytoflow\\tests -N 2"

after_test:
  # Install packaging requirements
  - conda install --yes --quiet "sphinx==1.8.1"

  # when PyInstaller supports Conda's qt5, we'll go back to using the 
  # version from PyPI.  In the meantime, we're going to use a submodule
  # that has a version that works.
  # - pip.exe install "pyinstaller==3.4.0"
  - git submodule init
  - git submodule update
  - cd packaging\pyinstaller
  - python setup.py install
  - cd ..\..
  
  # Build PyPI packages
  - "python setup.py build_sphinx -b embedded_help"
  - "python setup.py bdist_wheel"
  
  # Build one-click
  - "pyinstaller packaging/pyinstaller.spec"
  - "pyi-archive_viewer -l dist\\cytoflow.exe"
  - set CONDA_TAG
  - set PYTHON_ARCH
  - dir dist
  - "IF %PYTHON_ARCH% EQU 32 move dist\\cytoflow.exe dist\\cytoflow-%CONDA_TAG%-win32.exe"
  - "IF %PYTHON_ARCH% EQU 64 move dist\\cytoflow.exe dist\\cytoflow-%CONDA_TAG%-win-amd64.exe"
  - IF "%APPVEYOR_REPO_TAG%"=="false" python packaging\rename.py cytoflow-.*?(cp35.*whl) cytoflow-dev-\1 dist\*.whl
  
  # Move conda package to dist folder
  - deactivate
  - python packaging\move_conda_package.py
  
  - "IF %PYTHON_ARCH% EQU 32 move build\\lib.win32-3.6\\cytoflow\\utility\\logicle_ext\\_Logicle*.pyd dist\\"
  - "IF %PYTHON_ARCH% EQU 64 move build\\lib.win-amd64-3.6\\cytoflow\\utility\\logicle_ext\\_Logicle*.pyd dist\\"

on_success:
# from https://github.com/theochem/python-cython-ci-example/blob/master/.appveyor.yml
# Upload to anaconda, with the correct label derived from the version tag.
# This is virtually impossible with a normal dos batch script...
# It also contains an incredibly clunky way to avoid build failure when anaconda writes
# something harmless to stderr. The normal way does not work!
# & anaconda $parameters 2>&1
# Powershell should be called Powerhell!
  - ps:
      if (($Env:APPVEYOR_REPO_TAG -eq "true") -and
          ($Env:APPVEYOR_REPO_NAME -eq ${Env:GITHUB_REPO_NAME})) {
        $tar_glob = ".\dist\cytoflow-*.tar.bz2";
        Write-Host "tar_glob $tar_glob";
        if ($Env:APPVEYOR_REPO_TAG_NAME -like "*a*") {
          $anaconda_label = "alpha"
        } elseif ($Env:APPVEYOR_REPO_TAG_NAME -like "*b*") {
          $anaconda_label = "beta"
        } else {
          $anaconda_label = "main"
        };
        Write-Host "anaconda_label $anaconda_label";
        $parameters = '-t', "$Env:ANACONDA_TOKEN", 'upload', "$tar_glob", '-l',
                      "$anaconda_label", '--force', '--no-progress';
        & cmd /c 'anaconda 2>&1' $parameters;
        
      }

artifacts:
  - path: dist\*.*

deploy:
  - provider: GitHub
    description: 'Cytoflow release'
    auth_token:
      secure: VVuhKeMWCRbcFWTVdrIbOuKkgnOqsQnCF3ZXl9SsE5YiCmuuYP1YxmII2ZuAp0lv
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true        # deploy on tag   

  - provider: BinTray
    username: bpteague
    api_key:
      secure: J1xtgBNfGlyHwokEnESgGsM01Oe/ZBYZF/DzWDutMYtOTCd4bJdmT1kZsirim/Gp
    subject: bpteague
    repo: cytoflow
    package: cytoflow
    version: latest
    publish: true
    override: true
    explode: false
    artifact: /(.*\.whl|.*\.bz2|.*\.pyd)/
    on:
       appveyor_repo_tag: true        # deploy on tag   

  - provider: BinTray
    username: bpteague
    api_key:
      secure: J1xtgBNfGlyHwokEnESgGsM01Oe/ZBYZF/DzWDutMYtOTCd4bJdmT1kZsirim/Gp
    subject: bpteague
    repo: cytoflow
    package: cytoflow
    version: latest
    publish: true
    override: true
    explode: false
    artifact: /(.*\.whl|.*\.bz2|.*\.pyd)/
    on:
        branch: master

  - provider: BinTray
    username: bpteague
    api_key:
      secure: J1xtgBNfGlyHwokEnESgGsM01Oe/ZBYZF/DzWDutMYtOTCd4bJdmT1kZsirim/Gp
    subject: bpteague
    repo: cytoflow
    package: cytoflow
    version: latest
    publish: true
    override: true
    explode: false
    artifact: /(.*\.whl|.*\.bz2|.*\.pyd)/
    on:
        branch: packaging
        

