name: cytoflow
channels:
 - cytoflow
 
dependencies:
    - python==3.8.5
    - numpy==1.20.2
    - pandas==1.2.5
    - matplotlib==3.3.4
    - bottleneck==1.3.2
    - numexpr==2.7.3
    - scipy==1.6.2
    - scikit-learn==0.24.2
    - seaborn==0.11.1
    - statsmodels==0.12.2
    - natsort==7.1.1

    - traits==6.2.0
    - traitsui==7.1.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.1.3
    - python-dateutil==2.8.1
    - importlib_resources==5.2.0

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - fcsparser==0.2.1bt1
    - camel==0.1.2
    - yapf==0.30.0
    
    - notebook
