name: cytoflow
channels:
 - cytoflow
 
dependencies:
    - python==3.8.12
    - numpy==1.21.2
    - pandas==1.3.5
    - matplotlib==3.5.0
    - bottleneck==1.3.2
    - numexpr==2.8.1
    - scipy==1.7.3
    - scikit-learn==1.0.1
    - seaborn==0.11.2
    - statsmodels==0.13.0
    - natsort==7.1.1
    - numba==0.53.1

    - traits==6.2.0
    - traitsui==7.2.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.1.3
    - python-dateutil==2.8.2
    - importlib_resources==5.2.0

    - qt==5.15.7
    - pyqt==5.15.7
    - pyqtwebengine==5.15.7

    - camel==0.1.2
    - yapf==0.30.0
    
    - notebook
    
    - nomkl # [not win]
