name: cytoflow
channels:
 - cytoflow
 
dependencies:
    - python==3.8.12
    - numpy==1.21.2
    - pandas==1.3.5
    - matplotlib==3.5.0
    - bottleneck==1.3.7
    - numexpr==2.8.1
    - scipy==1.7.3
    - scikit-learn==1.2.2
    - seaborn==0.12.2
    - statsmodels==0.13.0
    - natsort==7.1.1
    - llvmlite-0.40.0
    - numba==0.57.0
    - fcsparser==0.2.6
    - umap-learn==0.5.3
    - hdbscan==0.8.29

    - traits==6.2.0
    - traitsui==7.2.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.1.3
    - python-dateutil==2.8.2
    - importlib_resources==5.2.0

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - camel==0.1.2
    - yapf==0.30.0
    
    - notebook
    
    - nomkl # [not win]
