name: cytoflow
channels:
 - bpteague
 
dependencies:
    - python==3.6.10
    - numpy==1.18.1
    - pandas==1.0.5
    - matplotlib==3.1.3
    - bottleneck==1.3.2
    - numexpr==2.7.1
    - scipy==1.4.1
    - scikit-learn==0.22.1
    - seaborn==0.10.0
    - statsmodels==0.11.0

    - traits==6.1.0
    - traitsui==7.0.1
    - pyface==7.0.1
    - envisage==4.9.2
    - nbformat==5.0.4
    - python-dateutil==2.8.1

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - fcsparser==0.2.0
    - camel==0.1.2
    - yapf==0.22.0

    - mock==4.0.1
    - sphinx==2.4.4
    
    - notebook
