name: cytoflow
channels:
 - defaults
 - cytoflow
 - conda-forge
 
dependencies:
    - python==3.13.5
    - numpy==2.2.5
    - pandas==2.2.3
    - matplotlib==3.10.0
    - bottleneck==1.4.2
    - numexpr==2.10.1
    - scipy==1.15.3
    - scikit-learn==1.6.1
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - natsort==7.1.1
    - numba==0.61.2
    - opentsne==1.0.2
    - python-igraph==0.11.9
    - scikit-fda==0.10.1

    - traits==7.0.2
    - traitsui==8.0.0
    - pyface==8.0.0
    - conda-forge::envisage==7.0.4
    - conda-forge::apptools==5.3.1
    - nbformat==5.10.4
    - python-dateutil==2.9.0post0
    - importlib_resources==6.4.0

    - qt==5.15.*
    - pyqt==5.15.*
    - pyqtwebengine=5.15.*

    - cytoflow::camel==0.1.2
    - yapf==0.40.2
    
    - ipympl
    - notebook
    