name: cytoflow
channels:
 - cytoflow
 
dependencies:
    - python=3.11.11
    - numpy==1.26.4
    - pandas==2.2.3
    - matplotlib==3.9.2
    - bottleneck==1.4.2
    - numexpr==2.10.1
    - scipy==1.14.1
    - scikit-learn==1.5.1
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - natsort==7.1.1
    - numba==0.60.0

    - traits==6.2.0
    - traitsui==7.2.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.10.4
    - python-dateutil==2.9.0post0
    - importlib_resources==6.4.0

    - qt==5.15.*
    - pyqt==5.15.*
    - pyqtwebengine=5.15.*

    - camel==0.1.2
    - yapf==0.30.0
    
    - notebook
    
    - nomkl # [not win]
