name: cytoflow
channels:
 - bpteague
 
dependencies:
    - python==3.8.5
    - numpy==1.19.2
    - pandas==1.2.1
    - matplotlib==3.3.2
    - bottleneck==1.3.2
    - numexpr==2.7.2
    - scipy==1.6.0
    - scikit-learn==0.23.2
    - seaborn==0.11.1
    - statsmodels==0.12.1
    - natsort==7.1.1

    - traits==6.2.0
    - traitsui==7.1.1
    - pyface==7.2.0
    - envisage==5.0.0
    - nbformat==5.0.8
    - python-dateutil==2.8.1

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - fcsparser==0.2.1
    - camel==0.1.2
    - yapf==0.30.0
    
    - notebook
