name: test-and-package
on: [push]
jobs:
  build-and-test-linux:
    name: Run cytoflow unit tests on linux
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Get branch, tag names
      id: branch_name
      run: |
        git fetch --prune --unshallow --tags
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
    - name: Git describe
      run: git describe --tags
          
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Configure conda
      run: |
        conda update --yes conda
        conda config --add channels bpteague
        conda install --yes --quiet anaconda-client conda-build
        
    - name: Build conda package
      env:
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      run: |
        conda render package/conda_recipes/cytoflow
        conda build package/conda_recipes/cytoflow
        
    - name: Create test/packaging environment
      run: |
        conda create --yes --quiet --name=cytoflow python=3.6.12 nomkl
        source activate cytoflow
        conda install --yes --quiet --use-local --only-deps cytoflow
    
    - name: Install package locally
      run: |
        source activate cytoflow
        python setup.py develop
        
    - name: Install nose2
      run: |
        source activate cytoflow
        conda install --yes --quiet pip
        pip install nose2
        
    - name: Run nose2
      run: |
        source activate cytoflow
        nose2 -c package/nose2.cfg -s cytoflow/tests -N 2
        
    - name: Install packaging deps
      run: |
        source activate cytoflow
        conda install --yes --quiet 'sphinx==3.2.1'
        pip install "pyinstaller==3.6"
        
    - name: Build embedded help docs
      run: |
        source activate cytoflow
        python setup.py build_sphinx -b embedded_help
        
    - name: Build source dist
      run: |
        source activate cytoflow
        python setup.py sdist
        
    - name: Build wheel
      run: |
        source activate cytoflow
        python setup.py bdist_wheel
        
    - name: Build GUI binary
      run: |
        source activate cytoflow
        python package/pyinstaller-local.py package/pyinstaller.spec
        
    - name: Zip up examples
      run: |
        cd docs
        zip -r cytoflow-{{ steps.branch_name.outputs.SOURCE_NAME }}-examples-basic.zip examples-basic
        zip -r cytoflow-{{ steps.branch_name.outputs.SOURCE_NAME }}-examples-advanced.zip examples-advanced
        mv cytoflow-{{ steps.branch_name.outputs.SOURCE_NAME }}-examples-*.zip ../dist
        
    - name: Move C++ extensions into the dist folder
      run: |
        cp `find build | grep "\.so$"` dist/
        python package/move_conda_package.py
        
    - name: List dist
      run: ls dist/
      
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list

        